//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IUProdPack.WsPiciz {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsPiciz.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Cliente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SepararFormulario", ReplyAction="*")]
        IUProdPack.WsPiciz.SepararFormularioResponse SepararFormulario(IUProdPack.WsPiciz.SepararFormularioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SepararFormulario", ReplyAction="*")]
        System.Threading.Tasks.Task<IUProdPack.WsPiciz.SepararFormularioResponse> SepararFormularioAsync(IUProdPack.WsPiciz.SepararFormularioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idFMM del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CompletarFormulario", ReplyAction="*")]
        IUProdPack.WsPiciz.CompletarFormularioResponse CompletarFormulario(IUProdPack.WsPiciz.CompletarFormularioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CompletarFormulario", ReplyAction="*")]
        System.Threading.Tasks.Task<IUProdPack.WsPiciz.CompletarFormularioResponse> CompletarFormularioAsync(IUProdPack.WsPiciz.CompletarFormularioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Cliente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarFormulario", ReplyAction="*")]
        IUProdPack.WsPiciz.RegistrarFormularioResponse RegistrarFormulario(IUProdPack.WsPiciz.RegistrarFormularioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarFormulario", ReplyAction="*")]
        System.Threading.Tasks.Task<IUProdPack.WsPiciz.RegistrarFormularioResponse> RegistrarFormularioAsync(IUProdPack.WsPiciz.RegistrarFormularioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SepararFormularioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SepararFormulario", Namespace="http://tempuri.org/", Order=0)]
        public IUProdPack.WsPiciz.SepararFormularioRequestBody Body;
        
        public SepararFormularioRequest() {
        }
        
        public SepararFormularioRequest(IUProdPack.WsPiciz.SepararFormularioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SepararFormularioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int empid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int tipoDoc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Prefijo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Comprobante;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime Fecha;
        
        public SepararFormularioRequestBody() {
        }
        
        public SepararFormularioRequestBody(int empid, string Cliente, int tipoDoc, string Prefijo, string Comprobante, System.DateTime Fecha) {
            this.empid = empid;
            this.Cliente = Cliente;
            this.tipoDoc = tipoDoc;
            this.Prefijo = Prefijo;
            this.Comprobante = Comprobante;
            this.Fecha = Fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SepararFormularioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SepararFormularioResponse", Namespace="http://tempuri.org/", Order=0)]
        public IUProdPack.WsPiciz.SepararFormularioResponseBody Body;
        
        public SepararFormularioResponse() {
        }
        
        public SepararFormularioResponse(IUProdPack.WsPiciz.SepararFormularioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SepararFormularioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal SepararFormularioResult;
        
        public SepararFormularioResponseBody() {
        }
        
        public SepararFormularioResponseBody(decimal SepararFormularioResult) {
            this.SepararFormularioResult = SepararFormularioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CompletarFormularioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CompletarFormulario", Namespace="http://tempuri.org/", Order=0)]
        public IUProdPack.WsPiciz.CompletarFormularioRequestBody Body;
        
        public CompletarFormularioRequest() {
        }
        
        public CompletarFormularioRequest(IUProdPack.WsPiciz.CompletarFormularioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CompletarFormularioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int empid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idFMM;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int tipoDoc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Prefijo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Comprobante;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime Fecha;
        
        public CompletarFormularioRequestBody() {
        }
        
        public CompletarFormularioRequestBody(int empid, string idFMM, string Cliente, int tipoDoc, string Prefijo, string Comprobante, System.DateTime Fecha) {
            this.empid = empid;
            this.idFMM = idFMM;
            this.Cliente = Cliente;
            this.tipoDoc = tipoDoc;
            this.Prefijo = Prefijo;
            this.Comprobante = Comprobante;
            this.Fecha = Fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CompletarFormularioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CompletarFormularioResponse", Namespace="http://tempuri.org/", Order=0)]
        public IUProdPack.WsPiciz.CompletarFormularioResponseBody Body;
        
        public CompletarFormularioResponse() {
        }
        
        public CompletarFormularioResponse(IUProdPack.WsPiciz.CompletarFormularioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CompletarFormularioResponseBody {
        
        public CompletarFormularioResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarFormularioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarFormulario", Namespace="http://tempuri.org/", Order=0)]
        public IUProdPack.WsPiciz.RegistrarFormularioRequestBody Body;
        
        public RegistrarFormularioRequest() {
        }
        
        public RegistrarFormularioRequest(IUProdPack.WsPiciz.RegistrarFormularioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarFormularioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int empid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int tipoDoc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Prefijo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Comprobante;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime Fecha;
        
        public RegistrarFormularioRequestBody() {
        }
        
        public RegistrarFormularioRequestBody(int empid, string Cliente, int tipoDoc, string Prefijo, string Comprobante, System.DateTime Fecha) {
            this.empid = empid;
            this.Cliente = Cliente;
            this.tipoDoc = tipoDoc;
            this.Prefijo = Prefijo;
            this.Comprobante = Comprobante;
            this.Fecha = Fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarFormularioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarFormularioResponse", Namespace="http://tempuri.org/", Order=0)]
        public IUProdPack.WsPiciz.RegistrarFormularioResponseBody Body;
        
        public RegistrarFormularioResponse() {
        }
        
        public RegistrarFormularioResponse(IUProdPack.WsPiciz.RegistrarFormularioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RegistrarFormularioResponseBody {
        
        public RegistrarFormularioResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : IUProdPack.WsPiciz.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<IUProdPack.WsPiciz.ServiceSoap>, IUProdPack.WsPiciz.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IUProdPack.WsPiciz.SepararFormularioResponse IUProdPack.WsPiciz.ServiceSoap.SepararFormulario(IUProdPack.WsPiciz.SepararFormularioRequest request) {
            return base.Channel.SepararFormulario(request);
        }
        
        public decimal SepararFormulario(int empid, string Cliente, int tipoDoc, string Prefijo, string Comprobante, System.DateTime Fecha) {
            IUProdPack.WsPiciz.SepararFormularioRequest inValue = new IUProdPack.WsPiciz.SepararFormularioRequest();
            inValue.Body = new IUProdPack.WsPiciz.SepararFormularioRequestBody();
            inValue.Body.empid = empid;
            inValue.Body.Cliente = Cliente;
            inValue.Body.tipoDoc = tipoDoc;
            inValue.Body.Prefijo = Prefijo;
            inValue.Body.Comprobante = Comprobante;
            inValue.Body.Fecha = Fecha;
            IUProdPack.WsPiciz.SepararFormularioResponse retVal = ((IUProdPack.WsPiciz.ServiceSoap)(this)).SepararFormulario(inValue);
            return retVal.Body.SepararFormularioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IUProdPack.WsPiciz.SepararFormularioResponse> IUProdPack.WsPiciz.ServiceSoap.SepararFormularioAsync(IUProdPack.WsPiciz.SepararFormularioRequest request) {
            return base.Channel.SepararFormularioAsync(request);
        }
        
        public System.Threading.Tasks.Task<IUProdPack.WsPiciz.SepararFormularioResponse> SepararFormularioAsync(int empid, string Cliente, int tipoDoc, string Prefijo, string Comprobante, System.DateTime Fecha) {
            IUProdPack.WsPiciz.SepararFormularioRequest inValue = new IUProdPack.WsPiciz.SepararFormularioRequest();
            inValue.Body = new IUProdPack.WsPiciz.SepararFormularioRequestBody();
            inValue.Body.empid = empid;
            inValue.Body.Cliente = Cliente;
            inValue.Body.tipoDoc = tipoDoc;
            inValue.Body.Prefijo = Prefijo;
            inValue.Body.Comprobante = Comprobante;
            inValue.Body.Fecha = Fecha;
            return ((IUProdPack.WsPiciz.ServiceSoap)(this)).SepararFormularioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IUProdPack.WsPiciz.CompletarFormularioResponse IUProdPack.WsPiciz.ServiceSoap.CompletarFormulario(IUProdPack.WsPiciz.CompletarFormularioRequest request) {
            return base.Channel.CompletarFormulario(request);
        }
        
        public void CompletarFormulario(int empid, string idFMM, string Cliente, int tipoDoc, string Prefijo, string Comprobante, System.DateTime Fecha) {
            IUProdPack.WsPiciz.CompletarFormularioRequest inValue = new IUProdPack.WsPiciz.CompletarFormularioRequest();
            inValue.Body = new IUProdPack.WsPiciz.CompletarFormularioRequestBody();
            inValue.Body.empid = empid;
            inValue.Body.idFMM = idFMM;
            inValue.Body.Cliente = Cliente;
            inValue.Body.tipoDoc = tipoDoc;
            inValue.Body.Prefijo = Prefijo;
            inValue.Body.Comprobante = Comprobante;
            inValue.Body.Fecha = Fecha;
            IUProdPack.WsPiciz.CompletarFormularioResponse retVal = ((IUProdPack.WsPiciz.ServiceSoap)(this)).CompletarFormulario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IUProdPack.WsPiciz.CompletarFormularioResponse> IUProdPack.WsPiciz.ServiceSoap.CompletarFormularioAsync(IUProdPack.WsPiciz.CompletarFormularioRequest request) {
            return base.Channel.CompletarFormularioAsync(request);
        }
        
        public System.Threading.Tasks.Task<IUProdPack.WsPiciz.CompletarFormularioResponse> CompletarFormularioAsync(int empid, string idFMM, string Cliente, int tipoDoc, string Prefijo, string Comprobante, System.DateTime Fecha) {
            IUProdPack.WsPiciz.CompletarFormularioRequest inValue = new IUProdPack.WsPiciz.CompletarFormularioRequest();
            inValue.Body = new IUProdPack.WsPiciz.CompletarFormularioRequestBody();
            inValue.Body.empid = empid;
            inValue.Body.idFMM = idFMM;
            inValue.Body.Cliente = Cliente;
            inValue.Body.tipoDoc = tipoDoc;
            inValue.Body.Prefijo = Prefijo;
            inValue.Body.Comprobante = Comprobante;
            inValue.Body.Fecha = Fecha;
            return ((IUProdPack.WsPiciz.ServiceSoap)(this)).CompletarFormularioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IUProdPack.WsPiciz.RegistrarFormularioResponse IUProdPack.WsPiciz.ServiceSoap.RegistrarFormulario(IUProdPack.WsPiciz.RegistrarFormularioRequest request) {
            return base.Channel.RegistrarFormulario(request);
        }
        
        public void RegistrarFormulario(int empid, string Cliente, int tipoDoc, string Prefijo, string Comprobante, System.DateTime Fecha) {
            IUProdPack.WsPiciz.RegistrarFormularioRequest inValue = new IUProdPack.WsPiciz.RegistrarFormularioRequest();
            inValue.Body = new IUProdPack.WsPiciz.RegistrarFormularioRequestBody();
            inValue.Body.empid = empid;
            inValue.Body.Cliente = Cliente;
            inValue.Body.tipoDoc = tipoDoc;
            inValue.Body.Prefijo = Prefijo;
            inValue.Body.Comprobante = Comprobante;
            inValue.Body.Fecha = Fecha;
            IUProdPack.WsPiciz.RegistrarFormularioResponse retVal = ((IUProdPack.WsPiciz.ServiceSoap)(this)).RegistrarFormulario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IUProdPack.WsPiciz.RegistrarFormularioResponse> IUProdPack.WsPiciz.ServiceSoap.RegistrarFormularioAsync(IUProdPack.WsPiciz.RegistrarFormularioRequest request) {
            return base.Channel.RegistrarFormularioAsync(request);
        }
        
        public System.Threading.Tasks.Task<IUProdPack.WsPiciz.RegistrarFormularioResponse> RegistrarFormularioAsync(int empid, string Cliente, int tipoDoc, string Prefijo, string Comprobante, System.DateTime Fecha) {
            IUProdPack.WsPiciz.RegistrarFormularioRequest inValue = new IUProdPack.WsPiciz.RegistrarFormularioRequest();
            inValue.Body = new IUProdPack.WsPiciz.RegistrarFormularioRequestBody();
            inValue.Body.empid = empid;
            inValue.Body.Cliente = Cliente;
            inValue.Body.tipoDoc = tipoDoc;
            inValue.Body.Prefijo = Prefijo;
            inValue.Body.Comprobante = Comprobante;
            inValue.Body.Fecha = Fecha;
            return ((IUProdPack.WsPiciz.ServiceSoap)(this)).RegistrarFormularioAsync(inValue);
        }
    }
}
