//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IUReportes.WsReportes {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsReportes.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CargarReporte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CargarReporte(string Usuario, string Password, string NomConexion, int _TipoDoc, string _Prefijo, string _Cliente, string _NumDoc, System.DateTime _FechaGen, string _Comprobante, string _Observaciones, int _TipoImpresion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CargarReporte", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> CargarReporteAsync(string Usuario, string Password, string NomConexion, int _TipoDoc, string _Prefijo, string _Cliente, string _NumDoc, System.DateTime _FechaGen, string _Comprobante, string _Observaciones, int _TipoImpresion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : IUReportes.WsReportes.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<IUReportes.WsReportes.ServiceSoap>, IUReportes.WsReportes.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet CargarReporte(string Usuario, string Password, string NomConexion, int _TipoDoc, string _Prefijo, string _Cliente, string _NumDoc, System.DateTime _FechaGen, string _Comprobante, string _Observaciones, int _TipoImpresion) {
            return base.Channel.CargarReporte(Usuario, Password, NomConexion, _TipoDoc, _Prefijo, _Cliente, _NumDoc, _FechaGen, _Comprobante, _Observaciones, _TipoImpresion);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> CargarReporteAsync(string Usuario, string Password, string NomConexion, int _TipoDoc, string _Prefijo, string _Cliente, string _NumDoc, System.DateTime _FechaGen, string _Comprobante, string _Observaciones, int _TipoImpresion) {
            return base.Channel.CargarReporteAsync(Usuario, Password, NomConexion, _TipoDoc, _Prefijo, _Cliente, _NumDoc, _FechaGen, _Comprobante, _Observaciones, _TipoImpresion);
        }
    }
}
